CREATE DATABASE IF NOT EXISTS TIENDA;

USE TIENDA;

CREATE TABLE IF NOT EXISTS T_USUARIOS(
    ID_USUARIO INT (11) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR (100) NOT NULL,
    APELLIDOS VARCHAR (100) NOT NULL,
    EMAIL VARCHAR (200) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    ROL VARCHAR (20),
    IMAGEN VARCHAR (255),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_EMAIL UNIQUE(EMAIL)

)ENGINE=INNODB;

INSERT INTO t_usuarios VALUES (NULL, "ADMIN","ADMIN","ADMIN@ADMIN.COM", 123,"ADMIN","IMAGEN");