CREATE DATABASE IF NOT EXISTS TIENDA;

USE TIENDA;

CREATE TABLE IF NOT EXISTS T_USUARIOS(
    ID_USUARIO INT (11) AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR (100) NOT NULL,
    APELLIDOS VARCHAR (100) NOT NULL,
    EMAIL VARCHAR (200) NOT NULL,
    PASSWORD VARCHAR (255) NOT NULL,
    ROL VARCHAR (20),
    IMAGEN VARCHAR (255),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UQ_EMAIL UNIQUE(EMAIL)

)ENGINE=INNODB;

INSERT INTO t_usuarios VALUES (NULL, "ADMIN","ADMIN","ADMIN@ADMIN.COM", 123,"ADMIN","IMAGEN");

CREATE TABLE IF NOT EXISTS T_CATEGORIAS(
ID_CATEGORIA INT(11) AUTO_INCREMENT NOT NULL,
NOMBRE_CATEGORIA VARCHAR (100) NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA)
)ENGINE=INNODB;

INSERT INTO T_CATEGORIAS VALUES (NULL,'CONSTRUCCION'),(NULL,'ELECTRICOS'),(NULL,'PISOS');

CREATE TABLE IF NOT EXISTS T_PRODUCTOS(
    ID_PRODUCTO INT (11) AUTO_INCREMENT NOT NULL,
    NOMBRE_PRODUCTO VARCHAR (100) NOT NULL,
    PRECIO FLOAT (100,2) NOT NULL,
    STOCK INT(11) NOT NULL,
    OFERTA VARCHAR (50) NOT NULL,
    FECHA DATE,
    IMAGEN VARCHAR (255),
    ID_CATEGORIA INT (11) NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO),
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES T_CATEGORIAS (ID_CATEGORIA)
)ENGINE=INNODB;

CREATE TABLE IF NOT EXISTS T_PEDIDOS(
    ID_PEDIDO INT (11) AUTO_INCREMENT NOT NULL,
    FECHA DATE NOT NULL,
    ID_USUARIO INT (11) NOT NULL,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (ID_PEDIDO),
    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES T_USUARIOS (ID_USUARIO)


)ENGINE=INNODB;